config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
#  devise_scope :user do
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    # get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    # get 'github', to: 'omniauth_callbacks#github', as: :user_github_omniauth_callback
 # end

  root 'main#index'

  get '/our-items', to: 'main#our_items'
  get '/our-items/filter/:filter', to: 'main#set_user_filter', as: :set_user_filter
  get '/our-items/:item_id/toggle_claim', to: 'main#toggle_claim', as: :toggle_claim_item

  get '/our-users', to: 'main#our_users'

  get '/our-finances', to: 'main#our_finances'

  get '/change_user/:id', to: 'application#change_user', as: :change_user

  get '/start_crowdfunding/:item_id', to: 'main#start_crowdfunding', as: :start_crowdfunding

  resources :items do
    get "image", :on => :member
  end

  # resources :users

  resource :campaigns
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  FILTER_ALL = ['claims', 'purchased', 'other']
  # before_action :set_current_user
  before_action :set_session_filter

  def index
    case session[:active_tab]
      when nil, our_items_path
        redirect_to our_items_path
      when our_users_path
        redirect_to our_users_path
      when our_finances_path
        redirect_to our_finances_path
    end
  end

  def our_items
    session[:active_tab] = our_items_path
    set_items
    render :index
  end

  def our_users
    session[:active_tab] = our_users_path
    @users               = User.all
    render :index
  end

  def our_finances
    session[:active_tab] = our_finances_path
    render :index
  end

  def toggle_claim
    item = Item.find(params[:item_id])
    set_items

    if item.claimers.exists? current_user.id
      item.claimers.delete current_user
    else
      item.claimers << current_user
    end

    item.reload
    current_user.reload

    respond_to do |format|
      format.js do
        content = render_to_string partial: 'items/item', locals: { item: item, current_user: current_user }
        render :replace_element, locals: {
            selector: "#item_#{item.id}",
            content: content,
            location: "#{toggle_claim_item_path(params[:item_id])}"
        }
      end
      format.html { render :index }
    end
  end


  def set_user_filter
    user_filters = (params[:filter] || session[:filter] || 'all')
                       .split( /([\+\-]+\w+)/ )
                       .select { |i| not i.empty? }

    user_filters.each do |user_filter|
      flag = user_filter[0]
      if flag == '+' || flag == '-'
        user_filter = user_filter[1..-1]
      else
        flag = '^'
      end

      if user_filter == 'all'
        session[:filter] = Set.new FILTER_ALL
        break
      elsif user_filter == 'reset'
        session[:filter] = Set.new []
        break
      elsif ['claims', 'purchased', 'other'].include? user_filter
        if flag == '+'
          session[:filter] = session[:filter].to_set.add user_filter
        else
          session[:filter] = session[:filter].to_set.delete user_filter
        end
      end
    end

    set_items
    respond_to do |format|
      format.js do
        content = render_to_string partial: 'items'
        render :replace_element, locals: {
            selector: '#our-items',
            content: content,
            location: "#{our_items_path}/filter/#{params[:filter]}"
        }
      end
      format.html do
        render :index
      end
    end
  end

  def start_crowdfunding
    respond_to do |format|
      format.js do
        @uuid   = SecureRandom.uuid
        @result = render_to_string partial: 'main/items'
        render 'replace_main'
      end
    end
  end


  private
  def set_items
    user   = current_user
    @items = []
    if session[:filter].size == FILTER_ALL.size
      @items = Item.all
    else
      @items += user.claim_items - user.purchase_items if session[:filter].include?('claims')
      @items += user.purchase_items if session[:filter].include?('purchased')
      @items += user.other_items if session[:filter].include?('other')
    end
  end

  def set_session_filter
    session[:filter] ||= Set.new FILTER_ALL
  end
end

app/helpers/main_helper.rb
module MainHelper

  def filter_buttons(filter)
    filter_list = {
        'claims'    => 'Мои заявки',
        'purchased' => 'Оплачены',
        'other'     => 'Прочие'
    }

    links = []

    links << if filter.size == filter_list.size
               link_to 'Все', set_user_filter_path('reset'),
                       remote: true,
                       class:  "btn btn-primary"
             else
               link_to 'Все', set_user_filter_path('all'),
                       remote: true,
                       class:  "btn btn-default"
             end

    links << filter_list.map do |key, label|
      link_to label,
              set_user_filter_path( "#{session[:filter].include?(key) ? '-' : '+'}#{key}" ),
              remote: true,
              class:  "btn #{ session[:filter].include?(key) ? 'btn-primary' : 'btn-default' }"
    end
    links.join.html_safe
  end
end

app/views/main/_finances.html.erb
<div>

</div>

app/views/main/_items.html.erb
<div id="our-items" class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'Добавить предложение', new_item_path, class: 'btn btn-default' %>
    <div class="btn-group right-block">
      <%= filter_buttons(session[:filter]) %>
    </div>
  </div>
  <div id="main-content" class="panel-body" keep-scroll >
    <%= render @items %>
  </div>
</div>

app/views/main/_users.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th> Пользователь</th>
    <th style="padding-left: 30px;"> Предложил </th>
    <th style="padding-left: 30px;"> Подал заявку на </th>
    <th style="padding-left: 30px;"> Заплатил за </th>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, idx| %>
      <tr>
        <td> <%= idx + 1 %>. <%= user.name %> </td>
        <td>
          <% if user.offers.size > 0 %>
              <ol>
                <% user.offers.each do |item| %>
                    <li> <%= link_to item.description, item %> </li>
                <% end %>
              </ol>
          <% end %>
        </td>
        <td>
          <% if user.claim_items.size > 0 %>
              <ol>
                <% user.claim_items.each do |item| %>
                    <li> <%= link_to item.description, item %> </li>
                <% end %>
              </ol>
          <% end %>
        </td>
        <td>
          <% if user.purchase_items.size > 0 %>
              <ol>
                <% user.purchase_items.each do |item| %>
                    <li> <%= link_to item.description, item %> </li>
                <% end %>
              </ol>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/main/index.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      a.navbar-brand href="/" Slack Great Library

    ul.nav.navbar-nav
      - menu_items.each do |menu|
        = menuitem menu[:name], menu[:url], session[:active_tab] == menu[:url]

    ul.nav.navbar-nav.navbar-right
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#"
          = "#{current_user.name} (#{current_user.email})"
          span.caret

        ul.dropdown-menu
          - User.all.each do |user|
            - if user != current_user
              li = link_to "#{user.name} (#{user.email})", change_user_path(user.id)

      li
        a href=destroy_user_session_path
          span.glyphicon.glyphicon-log-in Выйти

div.main-page
  - case session[:active_tab]
  - when our_users_path
    = render 'users'
  - when our_finances_path
    = render 'finances'
  - else our_items_path
    = render 'items'

app/views/main/replace_element.js.erb
$('<%= selector %>').replaceWith("<%= j content %>");

<% unless location.nil? %>
  window.history.pushState(null, null, '<%= location %>');
<% end %>