config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
#  devise_scope :user do
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    # get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    # get 'github', to: 'omniauth_callbacks#github', as: :user_github_omniauth_callback
 # end

  root 'main#index'

  get '/our-items', to: 'main#our_items'
  get '/our-items/filter/:filter', to: 'main#set_user_filter', as: :set_user_filter
  get '/our-items/:item_id/toggle_claim', to: 'main#toggle_claim', as: :toggle_claim_item

  get '/our-users', to: 'main#our_users'

  get '/our-finances', to: 'main#our_finances'

  get '/change_user/:id', to: 'application#change_user', as: :change_user

  get '/start_crowdfunding/:item_id', to: 'main#start_crowdfunding', as: :start_crowdfunding

  resources :items do
    get "image", :on => :member
  end

  # resources :users

  resource :campaigns
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :offered_user, foreign_key: 'offered_by_id', class_name: 'User', primary_key: 'id'

  has_and_belongs_to_many :users

  has_many :purchases
  has_many :purchase_users, source: :user, through: :purchases

  has_many :claims
  has_many :claimers, through: :claims, source: :user

  has_many :campaigns

  default_scope { order :created_at }

  scope :other_items_for_user, -> (user_id) do
    joins(:purchases, :claims)
        .where.not(purchases: {user_id: user_id})
        .where.not(claims: {user_id: user_id})
  end

  # scope :new_requests_from_user, -> (user_id) do
  #   where.not(
  #       id: Item.joins(:purchases).where(purchases: { user_id: user_id })
  #   ).where(
  #       id: Item.joins(:claims).where(claims: { user_id: user_id })
  #   )
  # end
  #
  # scope :new_requests, -> do
  #   where.not(
  #       id: Item.joins(:purchases)
  #   ).where(
  #       id: Item.joins(:claims)
  #   )
  # end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :image]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item  = Item.new
    @users = User.all
  end

  # GET /items/1/edit
  def edit
    @users = User.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.offered_user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to our_items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    # p item_params
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to our_items_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to our_items_path, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
    if @item.data
      send_data @item.data,
                :type        => @item.mime_type,
                :filename    => "#{@item.filename}.jpg",
                :disposition => "inline"
    else
      redirect_to '/images/empty.png'
    end
  end


  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    if params[:item][:image]
      image_params = if params[:item][:image]
                       {
                           data:      params[:item][:image].read,
                           filename:  params[:item][:image].original_filename,
                           mime_type: params[:item][:image].content_type
                       }
                     end
    end

    params
        .require(:item)
        .permit(:description, :url, :price, :itemtype)
        .merge(image_params || {})
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="panel panel-default width-800">
  <div class="panel-heading">
    Введите информацию о предлагаемом продукте
  </div>
  <div class="panel-body">
    <%= form_for(item) do |f| %>
        <% if item.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

              <ul>
                <% item.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="item">
          <div class="preview-upload">
            <img id="preview" src="#" alt="Выберете файл" class="item_image clickable">
            <%= f.file_field :image, class: "form-control-2 hidden" %>
          </div>

          <div class="input-info">
            <table>
              <tr>
                <td class="row_title cell"> <%= f.label :itemtype, 'Название:' %> </td>
                <td class="cell">
                  <%= f.text_field :description, placeholder: 'Agile Web Development with Rails 5', class: "form-control-2 width-max" %>
                </td>
              </tr>
              <tr>
                <td class="row_title cell"> <%= f.label :itemtype, 'Вид товара:' %> </td>
                <td class="cell">
                  <%= f.text_field :itemtype, placeholder: 'книга, скринкаст, подкаст, доступ к сайту...', class: "form-control-2 width-400" %>
                </td>
              </tr>
              <tr>
                <td class="row_title cell"> <%= f.label :url, 'URL:' %> </td>
                <td class="cell">
                  <%= f.text_field :url, placeholder: 'http://', class: "form-control-2 width-400" %>
                </td>
              </tr>
              <tr>
                <td class="row_title cell"> <%= f.label :price, 'Цена:' %> </td>
                <td class="cell">
                  <%= f.text_field :price, placeholder: 'без копеек...', class: "form-control-2 width-200" %>
                </td>
              </tr>
              <tr>
                <td class="row_title cell"> <%= f.label :offered_by, 'Предложил:' %> </td>
                <td class="cell">
                  <%= current_user.name %>
                  <!-- %= collection_select :item, :offered_by, users, :id, :name, class: "form-control-2" % -->
                </td>
              </tr>
            </table>
          </div>
        </div>
    <% end %>
  </div>
  <div class="panel-footer text-right">
    <%= link_to 'Добавить', '#', onclick: "$('#new_item').submit()", class: "btn btn-primary" %>
  </div>
</div>

app/views/items/_item.html.slim
/ список заявителей через запятую
- claimer_links = map_link_to (User.list_requested item.id), :name
/ кол-во новых заявок
- claims_count  = User.list_requested(item.id).count
/ средняя цена с учетом новых заявок и уже оплаченной суммы
- median_price  = item.claimers.any? ? (item.price.to_f / item.claimers.count).ceil.to_i : item.price

.item id="item_#{item.id}"

  / Обложка
  = image_tag image_item_path(item), class: 'item_image'

  .info
    table

      / Название книги или краткое описание ресурса
      tr
        td.row_title.cell
        td.cell
          span.item-title = item.description

      / Вид товара: книга, скринкаст, прочее
      tr
        td.row_title.cell
        td.cell
          i = item.itemtype

      / Ссылка на магазин
      tr
        td.row_title.cell
          strong URL:
        td.cell
          a href=item.url = item.url

      / Цена продукта на момент покупки
      tr
        td.row_title.cell
          strong Цена:
        td.cell
          = item.price
          - if item.claimers.any?
            |  по #{median_price} с каждого

      / Кто добавил книгу в базу
      tr
        td.row_title.cell
          strong Предложил:
        td.cell
          - if item.offered_user
            = link_to item.offered_user.name, our_users_path

      / Новые заявки от людей, которые еще не покупали книгу
      tr
        td.row_title.cell
          strong Новые заявки:
          - if claims_count > 0
            td.cell
              | #{claims_count} чел (#{claimer_links})
          - else
            td.cell
              span style="color: red" нет желающих

      / Показывает кто донатил за книгу
      tr
        td.row_title.cell
          strong Скинулись:
          - if item.purchase_users.count > 0
            td.cell
              | #{item.purchase_users.count} чел
              | (#{map_link_to item.purchase_users, :name})
          - else
            td.cell
              span style="color: red" не скидывались

      / Кнопки управления
      tr
        td
        td.cell
          - if item.claimers.exists? current_user.id
            = danger_button 'Отозвать заявку', toggle_claim_item_path(item)
          - else
            = primary_button 'Подать заявку', toggle_claim_item_path(item)

          = primary_button 'Начать сбор денег', start_crowdfunding_path(item)

          - if item.offered_user == current_user
            = delete_button 'Удалить', item

          == yield(item) if block_given?

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', users: @users, item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div id="our-items" class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'Добавить предложение', new_item_path, class: 'btn btn-default' %>
    <div class="btn-group right-block">
      <%= filter_buttons(session[:filter]) %>
    </div>
  </div>
  <div id="main-content" class="panel-body" keep-scroll >
    <%= render partial: 'items/item', collection: @items, locals: {current_user: @current_user} %>
  </div>
</div>

app/views/items/new.html.erb
<%= render 'form', users: @users, item: @item %>

app/views/items/show.html.erb
<%= render 'item', item: @item do %>
  <div class="edit_back_btn_block">
    <%= link_to 'Edit', edit_item_path(@item) %> |
    <%= link_to 'Back', items_path %>
  </div>
<% end %>